import {
  Apple,
  Coffee,
  Cupcake,
  Fish,
  Hamburger,
  IceCreamCone,
  Lollipop,
  Utensils,
  Beer,
  CircleDollarSign,
  Wallet,
  Landmark,
  HandCoins,
  Car,
  Heart,
  ShoppingCart,
  CarTaxiFront,
  ShoppingBasket,
  Toothbrush,
  Hospital,
  Cross,
  Ambulance,
  BaggageClaim,
  FaceGrinning,
  BookBookmark,
  MailOpen,
  Phone,
  Headphones,
  SmartphoneCharging,
  Video,
  Clapperboard,
  Gift,
  Gem,
  Rose,
  Shirt,
  Store,
  BadgePercent,
  PaperBag,
  Plane,
  PlaneTakeoff,
  PlaneLanding,
  Cat,
  Dog,
  PawPrint,
  Bone,
  Pipette,
  Rabbit,
  Turtle,
  PersonStanding,
  Users,
  Baby,
  Bike,
  FishingRod,
  Dumbbell,
  TrainFront,
  MopSparkles,
  SportShoe,
  Medal,
  Volleyball,
  BookOpenCheck,
  NotepadText,
  LibraryBig,
  BookHeart,
  BookOpenText,
  StarCheck,
  Music,
  Drum,
  ClefTreble,
  MicVocal,
  Guitar,
  AlarmClockCheck,
  Siren,
  Scale,
  Mouth,
  MirrorRound,
  Houses,
  Handshake,
  Brush,
  Highlighter,
  LandPlot,
  Computer,
  Construction,
  Package,
  Puzzle,
  Wrench,
  Camera,
  Drill,
  Disc3,
  FaceAngry,
  FaceSlightlySmiling,
  PartyPopper,
  Star,
  CreditCardReader,
  Faucet,
  Candy,
  Martini,
  ChessKnight,
  ChessQueen,
  Club,
  Dices,
  Flame,
  FlameKindling,
  FlaskConical,
  Gamepad2,
  Ghost,
  Mountain,
  MonitorPc,
  Sprout,
  ToyBrick,
  AirVent,
  Bed,
  Birdhouse,
  CookingPot,
  RockingChair,
  Sofa,
  Toilet,
  Toolbox,
  Trash,
  BriefcaseMedical,
  HeartPulse,
  Ear,
  Cigarette,
  Drama,
  Piano,
  Tv,
  Binoculars,
  TreePalm,
  TentTree,
  Park,
  PlantPot,
  EvCharger,
  FerrisWheel,
  Ship,
  Stethoscope,
  Syringe,
  Flower2,
  Snowflake,
  Cake,
  HandHeart,
  WavesLadder,
  Sun,
  Palette,
  CircleParking,
  Ticket,
  Bath,
  CloudRainWind,
} from 'lucide-react';
import type { JSX } from 'react/jsx-runtime';

export const iconMapping: Record<number, JSX.Element> = {
  1: <Utensils />,
  2: <Apple />,
  3: <Fish />,
  4: <Lollipop />,
  5: <Cupcake />,
  6: <Hamburger />,
  7: <Coffee />,
  8: <IceCreamCone />,
  9: <Beer />,
  10: <CircleDollarSign />,
  11: <Wallet />,
  12: <Landmark />,
  13: <HandCoins />,
  14: <Car />,
  15: <Heart />,
  16: <ShoppingCart />,
  17: <CarTaxiFront />,
  18: <ShoppingBasket />,
  19: <Toothbrush />,
  20: <Hospital />,
  21: <Cross />,
  22: <Ambulance />,
  23: <BaggageClaim />,
  24: <FaceGrinning />,
  25: <BookBookmark />,
  26: <MailOpen />,
  27: <Phone />,
  28: <Headphones />,
  29: <SmartphoneCharging />,
  30: <Video />,
  31: <Clapperboard />,
  32: <Gift />,
  33: <Gem />,
  34: <Rose />,
  35: <Shirt />,
  36: <Store />,
  37: <BadgePercent />,
  38: <PaperBag />,
  39: <Plane />,
  40: <PlaneTakeoff />,
  41: <PlaneLanding />,
  42: <Cat />,
  43: <Dog />,
  44: <PawPrint />,
  45: <Bone />,
  46: <Pipette />,
  47: <Rabbit />,
  48: <Turtle />,
  49: <PersonStanding />,
  50: <Users />,
  51: <Baby />,
  52: <Bike />,
  53: <FishingRod />,
  54: <Dumbbell />,
  55: <TrainFront />,
  56: <MopSparkles />,
  57: <SportShoe />,
  58: <Medal />,
  59: <Volleyball />,
  60: <BookOpenCheck />,
  61: <NotepadText />,
  62: <LibraryBig />,
  63: <BookHeart />,
  64: <BookOpenText />,
  65: <StarCheck />,
  66: <Music />,
  67: <Drum />,
  68: <ClefTreble />,
  69: <MicVocal />,
  70: <Guitar />,
  71: <AlarmClockCheck />,
  72: <Siren />,
  73: <Scale />,
  74: <Mouth />,
  75: <MirrorRound />,
  76: <Houses />,
  77: <Handshake />,
  78: <Brush />,
  79: <Highlighter />,
  80: <LandPlot />,
  81: <Computer />,
  82: <Construction />,
  83: <Package />,
  84: <Puzzle />,
  85: <Wrench />,
  86: <Camera />,
  87: <Drill />,
  88: <Disc3 />,
  89: <FaceAngry />,
  90: <FaceSlightlySmiling />,
  92: <PartyPopper />,
  93: <Star />,
  94: <CreditCardReader />,
  95: <Faucet />,
  96: <Candy />,
  97: <Martini />,
  98: <ChessKnight />,
  99: <ChessQueen />,
  100: <Club />,
  101: <Dices />,
  102: <Flame />,
  103: <FlameKindling />,
  104: <FlaskConical />,
  105: <Gamepad2 />,
  106: <Ghost />,
  107: <Mountain />,
  108: <MonitorPc />,
  109: <Sprout />,
  110: <ToyBrick />,
  111: <AirVent />,
  112: <Bed />,
  113: <Birdhouse />,
  114: <CookingPot />,
  115: <RockingChair />,
  116: <Sofa />,
  117: <Toilet />,
  118: <Toolbox />,
  119: <Trash />,
  120: <BriefcaseMedical />,
  121: <HeartPulse />,
  122: <Ear />,
  123: <Cigarette />,
  124: <Drama />,
  125: <Piano />,
  126: <Tv />,
  127: <Binoculars />,
  128: <TreePalm />,
  129: <TentTree />,
  130: <Park />,
  131: <PlantPot />,
  132: <EvCharger />,
  133: <FerrisWheel />,
  134: <Ship />,
  135: <Stethoscope />,
  136: <Syringe />,
  137: <Flower2 />,
  138: <Snowflake />,
  139: <Cake />,
  140: <HandHeart />,
  142: <WavesLadder />,
  143: <Sun />,
  144: <Palette />,
  145: <CircleParking />,
  146: <Ticket />,
  147: <Bath />,
  148: <CloudRainWind />,
};
